{ inputs, ... }:
let
  # Single source of truth for scripts/fetch-sources.sh, the same way
  # `write-flake` (from flake-file) regenerates flake.nix: the .sh file is a
  # normal committed file, but its source of truth is this Nix string, not
  # hand-edits to the script itself. Both the generator (write-fetch-sources-script,
  # below) and the drift check (checks.check-fetch-sources-script) consume this
  # exact same value via pkgs.writeText, so they can never disagree with each
  # other - editing this string is the only way to change either.
  fetchSourcesScriptText = ''
    #!/usr/bin/env bash
    # Re-fetch the archived agentskills.io docs used by the
    # writing-agent-skills skill, stamping each with its source URL
    # and fetch date. Regenerated by `write-fetch-sources-script`
    # (modules/agent-skills/skill-builder.nix) - edit there, not
    # here; running the generator overwrites this file.
    set -euo pipefail

    dest="''${1:-$HOME/.claude/skills/writing-agent-skills/resources}"

    # Mirrors https://agentskills.io/llms.txt's page list - update
    # both this and the generator if the site adds/removes pages.
    slugs=(
      "client-implementation/adding-skills-support"
      "clients"
      "home"
      "skill-creation/best-practices"
      "skill-creation/evaluating-skills"
      "skill-creation/optimizing-descriptions"
      "skill-creation/quickstart"
      "skill-creation/using-scripts"
      "specification"
    )
    fetched="$(date -u +%Y-%m-%d)"

    for slug in "''${slugs[@]}"; do
      out="$dest/$slug.raw.md"
      mkdir -p "$(dirname "$out")"
      tmp="$(mktemp)"
      # site serves raw markdown natively at <path>.md - fetched
      # directly rather than scraped/converted, so this is the
      # actual authored source, not a lossy HTML round-trip.
      curl -fsSL "https://agentskills.io/$slug.md" -o "$tmp"
      {
        echo "**Source:** https://agentskills.io/$slug"
        echo "**Fetched:** $fetched"
        echo
        echo "---"
        echo
        cat "$tmp"
      } > "$out"
      rm -f "$tmp"
      echo "updated $out"
    done
  '';
in
{
  # Declared here too (not just borrowed from claude-desktop.nix) so this
  # aspect doesn't silently break if claude-desktop.nix is ever parked or
  # its own pog input removed - see modules/agent-skills/skill-builder/CLAUDE.md.
  flake-file.inputs.pog.url = "github:jpetrucciani/pog";

  # skill-builder/ is laid out like an actual Agent Skill directory
  # (scripts/, eventually SKILL.md) rather than loose tooling, since its
  # whole job is maintaining one (the writing-agent-skills Claude Code
  # skill at ~/.claude/skills/writing-agent-skills/) - not part of this
  # flake's system config, just personal tooling riding along on
  # hornicorn's package set the same way hornicorn-rebuild does.
  den.aspects.skill-builder = {
    nixos =
      { pkgs, ... }:
      let
        pog = inputs.pog.packages.${pkgs.stdenv.hostPlatform.system}.pog.pog;
        fetchSourcesScriptFile = pkgs.writeText "fetch-sources.sh" fetchSourcesScriptText;

        write-fetch-sources-script = pog {
          name = "write-fetch-sources-script";
          description = "Regenerate modules/agent-skills/skill-builder/scripts/fetch-sources.sh - edit fetchSourcesScriptText in modules/agent-skills/skill-builder.nix, not the .sh file directly";
          strict = true;
          script = helpers: with helpers; ''
            repo_root="$(git rev-parse --show-toplevel)"
            out="$repo_root/modules/agent-skills/skill-builder/scripts/fetch-sources.sh"
            mkdir -p "$(dirname "$out")"
            install -m755 ${fetchSourcesScriptFile} "$out"
            echo "wrote $out"
          '';
        };

        # Exercises the real fetch-sources.sh against the live site and
        # asserts on its actual output (non-empty, both stamps present) -
        # the network-dependent half of the test harness that
        # checks.check-fetch-sources-script can't cover, since `nix flake
        # check` sandboxes network access and this needs to hit
        # agentskills.io for real. Not wired into `nix flake check` for
        # that reason - run manually after touching fetchSourcesScriptText.
        test-fetch-sources = pog {
          name = "test-fetch-sources";
          description = "Smoke-test fetch-sources.sh against the live agentskills.io site - requires network, run manually (not part of `nix flake check`)";
          strict = true;
          script = helpers: with helpers; ''
            repo_root="$(git rev-parse --show-toplevel)"
            script="$repo_root/modules/agent-skills/skill-builder/scripts/fetch-sources.sh"
            dest="$(mktemp -d)"
            trap 'rm -rf "$dest"' EXIT

            bash "$script" "$dest"

            fail=0
            while IFS= read -r -d "" f; do
              if [[ ! -s "$f" ]]; then
                echo "FAIL: $f is empty" >&2
                fail=1
              elif ! grep -q '^\*\*Source:\*\* https://agentskills\.io/' "$f"; then
                echo "FAIL: $f missing **Source:** stamp" >&2
                fail=1
              elif ! grep -qE '^\*\*Fetched:\*\* [0-9]{4}-[0-9]{2}-[0-9]{2}$' "$f"; then
                echo "FAIL: $f missing **Fetched:** stamp" >&2
                fail=1
              else
                echo "PASS: $f ($(wc -l < "$f") lines)"
              fi
            done < <(find "$dest" -name '*.raw.md' -print0)

            if [[ "$fail" -ne 0 ]]; then
              echo "test-fetch-sources: one or more assertions failed" >&2
              exit 1
            fi
            echo "test-fetch-sources: all assertions passed"
          '';
        };
      in
      {
        environment.systemPackages = [
          write-fetch-sources-script
          test-fetch-sources
        ];
      };
  };

  # TDD-style drift check, same idea as flake-file's own check-flake-file:
  # fetchSourcesScriptText is the only place this content should be edited,
  # so a mismatch here means someone hand-edited scripts/fetch-sources.sh (or
  # edited the Nix string and forgot to regenerate) - not something a curl-based
  # test could catch anyway, since `nix flake check`'s sandbox has no network.
  perSystem =
    { pkgs, ... }:
    {
      checks.check-fetch-sources-script = pkgs.runCommand "check-fetch-sources-script" { } ''
        diff -u ${pkgs.writeText "fetch-sources.sh" fetchSourcesScriptText} ${./skill-builder/scripts/fetch-sources.sh} \
          || {
            echo "modules/agent-skills/skill-builder/scripts/fetch-sources.sh is out of date." >&2
            echo "Edit fetchSourcesScriptText in modules/agent-skills/skill-builder.nix, then run write-fetch-sources-script." >&2
            exit 1
          }
        touch $out
      '';
    };
}
