{ inputs, ... }:
{
  # skill-builder aspect - a pog script that (re)writes
  # modules/agent-skills/skill-builder/scripts/fetch-sources.sh, the same
  # way `write-flake` (from flake-file) regenerates flake.nix: the .sh file
  # is a normal committed file, but its source of truth is this heredoc, not
  # hand-edits to the script itself.
  #
  # skill-builder/ is laid out like an actual Agent Skill directory
  # (scripts/, eventually SKILL.md) rather than loose tooling, since its
  # whole job is maintaining one (the writing-agent-skills Claude Code
  # skill at ~/.claude/skills/writing-agent-skills/) - not part of this
  # flake's system config, just personal tooling riding along on
  # hornicorn's package set the same way hornicorn-rebuild does.
  den.aspects.skill-builder = {
    nixos =
      { pkgs, ... }:
      let
        pog = inputs.pog.packages.${pkgs.stdenv.hostPlatform.system}.pog.pog;

        write-fetch-sources-script = pog {
          name = "write-fetch-sources-script";
          description = "Regenerate modules/agent-skills/skill-builder/scripts/fetch-sources.sh - edit the heredoc in modules/agent-skills/skill-builder.nix, not the .sh file directly";
          strict = true;
          script = helpers: with helpers; ''
            repo_root="$(git rev-parse --show-toplevel)"
            out="$repo_root/modules/agent-skills/skill-builder/scripts/fetch-sources.sh"
            mkdir -p "$(dirname "$out")"

            cat >| "$out" <<'FETCH_SOURCES_SH'
            #!/usr/bin/env bash
            # Re-fetch the archived agentskills.io docs used by the
            # writing-agent-skills skill, stamping each with its source URL
            # and fetch date. Regenerated by `write-fetch-sources-script`
            # (modules/agent-skills/skill-builder.nix) - edit there, not
            # here; running the generator overwrites this file.
            set -euo pipefail

            dest="''${1:-$HOME/.claude/skills/writing-agent-skills/resources}"

            # Mirrors https://agentskills.io/llms.txt's page list - update
            # both this and the generator if the site adds/removes pages.
            slugs=(
              "client-implementation/adding-skills-support"
              "clients"
              "home"
              "skill-creation/best-practices"
              "skill-creation/evaluating-skills"
              "skill-creation/optimizing-descriptions"
              "skill-creation/quickstart"
              "skill-creation/using-scripts"
              "specification"
            )
            fetched="$(date -u +%Y-%m-%d)"

            for slug in "''${slugs[@]}"; do
              out="$dest/$slug.raw.md"
              mkdir -p "$(dirname "$out")"
              tmp="$(mktemp)"
              # site serves raw markdown natively at <path>.md - fetched
              # directly rather than scraped/converted, so this is the
              # actual authored source, not a lossy HTML round-trip.
              curl -fsSL "https://agentskills.io/$slug.md" -o "$tmp"
              {
                echo "**Source:** https://agentskills.io/$slug"
                echo "**Fetched:** $fetched"
                echo
                echo "---"
                echo
                cat "$tmp"
              } > "$out"
              rm -f "$tmp"
              echo "updated $out"
            done
            FETCH_SOURCES_SH

            chmod +x "$out"
            echo "wrote $out"
          '';
        };
      in
      {
        environment.systemPackages = [ write-fetch-sources-script ];
      };
  };
}
