#!/usr/bin/env bash
# Re-fetch the archived agentskills.io docs used by the
# writing-agent-skills skill, stamping each with its source URL
# and fetch date. Regenerated by `write-fetch-sources-script`
# (modules/agent-skills/skill-builder.nix) - edit there, not
# here; running the generator overwrites this file.
set -euo pipefail

dest="${1:-$HOME/.claude/skills/writing-agent-skills/resources}"

# Mirrors https://agentskills.io/llms.txt's page list - update
# both this and the generator if the site adds/removes pages.
slugs=(
  "client-implementation/adding-skills-support"
  "clients"
  "home"
  "skill-creation/best-practices"
  "skill-creation/evaluating-skills"
  "skill-creation/optimizing-descriptions"
  "skill-creation/quickstart"
  "skill-creation/using-scripts"
  "specification"
)
fetched="$(date -u +%Y-%m-%d)"

for slug in "${slugs[@]}"; do
  out="$dest/$slug.raw.md"
  mkdir -p "$(dirname "$out")"
  tmp="$(mktemp)"
  # site serves raw markdown natively at <path>.md - fetched
  # directly rather than scraped/converted, so this is the
  # actual authored source, not a lossy HTML round-trip.
  curl -fsSL "https://agentskills.io/$slug.md" -o "$tmp"
  {
    echo "**Source:** https://agentskills.io/$slug"
    echo "**Fetched:** $fetched"
    echo
    echo "---"
    echo
    cat "$tmp"
  } > "$out"
  rm -f "$tmp"
  echo "updated $out"
done
